name: Build and Deploy My App

on:
  push:
    branches:
      - main

env:
  IMAGE: jl115/my-app:${{ github.sha }}
  CONFIG_PATH: ./k8s
  ENV_FILE: .env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Write kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig && chmod 600 kubeconfig

      - name: Replace Variables in Manifests
        run: |
          apt-get update && apt-get install -y gettext
          mkdir rendered
          export $(cat ${{ env.ENV_FILE }} | xargs)
          for file in $(find ${{ env.CONFIG_PATH }} -name "*.yml" -o -name "*.yaml"); do
            envsubst < $file > rendered/$(basename $file)
          done

      - name: Apply Kubernetes Manifests
        run: |
          kubectl --kubeconfig=kubeconfig apply -f rendered
